#requires -Version 5.1
<#
    Tidy-Scripts.ps1
    The spring clean. It enforces one layout and sends everything else to the
    Recycle Bin.

    THE LAYOUT - five folders, and no loose files anywhere in <number>.Scripts
        <number>.Scripts\
            Run\          the bats you double-click, and nothing else
            Engine\       Run-All, Run-Website, this script
            Steps\        the nine .ps1 scripts that do the actual work
            Reference\    the paper index, the layout note, the readiness sheet
            Reports\      what the last few runs wrote

    ALSO BINNED
        One-off scripts that have already run, the superseded copy of
        PaperTracker.xlsx in Reference\ (the master lives in the Overview
        folder), and stray timestamped copies of the paper index.

    ANYTHING ELSE GOES
        Any other folder in <number>.Scripts, any file sitting at the top of it, and
        any file in Run\, Engine\ or Steps\ that is not a .ps1, .bat or .md,
        is sent to the Recycle Bin. Reports older than the newest few go too.
        Old scripts are not kept: the layout above is the tool set, and a
        superseded copy of a script is a thing to be confused by later.

    The Recycle Bin is the whole safety net, and it is enough - nothing here
    is unique, everything is either current or regenerated by the next run.
    If the Recycle Bin is not available the items move to _Deleted\ instead.

    Switches
        -Apply      do it (otherwise it lists and asks)
        -NoPause    no prompts, no "press Enter" - for use from Run-All
#>

param(
    [switch]$Apply,
    [switch]$NoPause
)

$ErrorActionPreference = 'Stop'

$me      = Split-Path -Parent $MyInvocation.MyCommand.Path   # ...\<number>.Scripts\Engine
$scripts = Split-Path -Parent $me                             # ...\<number>.Scripts

$LayoutDirs = @('Run', 'Engine', 'Steps', 'Reference', 'Reports')
$CodeDirs   = @('Run', 'Engine', 'Steps')
$CodeExt    = @('.ps1', '.bat', '.md')
$ReportKeep = 20

# Reference data that belongs in Reference\ if it turns up loose.
$ReferenceFiles = @('_PaperIndex.csv', '_PaperFolderLayout.md', '_CoreFiles.txt')

# One-off scripts that have done their job, and the bats that run them. A
# one-off kept after it has run is a thing to be puzzled by later, so they go.
$Spent = @(
    'Finalise-Content.ps1',    'Finalise-Content.bat',
    'Move-ToAdditional.ps1',   'Move-ToAdditional.bat',
    'Remove-StrayFolder.ps1',  'Remove-StrayFolder.bat',
    'Remove-TwinFolders.ps1',  'Remove-TwinFolders.bat',
    'Flatten-Overviews.ps1',   'Flatten-Overviews.bat',
    'Tidy-Section2.ps1',       'Fix-BookFolders.ps1'
)

# Superseded data files inside Reference\. PaperTracker.xlsx is the master status
# sheet and lives in the Overview folder; a second copy here drifts from it.
$SupersededReference = @('PaperTracker.xlsx', 'PaperReadiness.xlsx')

$doomed = New-Object System.Collections.Generic.List[object]
$rescue = New-Object System.Collections.Generic.List[object]

function Doom([string]$path, [string]$why) {
    $doomed.Add([pscustomobject]@{ Path = $path; Why = $why }) | Out-Null
}

function Close-Out {
    if (-not $NoPause) {
        Write-Host ''
        Write-Host 'Press Enter to close...'
        [void](Read-Host)
    }
}

# --- what does not belong -----------------------------------------------------

foreach ($f in (Get-ChildItem -LiteralPath $scripts -File -Force -EA SilentlyContinue)) {
    if ($ReferenceFiles -contains $f.Name) {
        $rescue.Add([pscustomobject]@{ From = $f.FullName; To = (Join-Path (Join-Path $scripts 'Reference') $f.Name) }) | Out-Null
        continue
    }
    Doom $f.FullName 'loose file at the top of <number>.Scripts'
}

foreach ($d in (Get-ChildItem -LiteralPath $scripts -Directory -Force -EA SilentlyContinue)) {
    if ($LayoutDirs -contains $d.Name) { continue }
    if ($d.Name -eq '_Deleted') { continue }   # the fallback bin; never bin it into itself
    Doom $d.FullName 'not one of the five folders'
}

foreach ($name in $CodeDirs) {
    $dir = Join-Path $scripts $name
    if (-not (Test-Path -LiteralPath $dir)) { continue }
    foreach ($f in (Get-ChildItem -LiteralPath $dir -File -Force -EA SilentlyContinue)) {
        if ($Spent -contains $f.Name) {
            Doom $f.FullName 'a one-off that has already run'
            continue
        }
        if ($CodeExt -contains $f.Extension.ToLower()) { continue }
        Doom $f.FullName ("not a script or a note, in {0}\" -f $name)
    }
    foreach ($sub in (Get-ChildItem -LiteralPath $dir -Directory -Force -EA SilentlyContinue)) {
        Doom $sub.FullName ("subfolder in {0}\ - these folders are flat" -f $name)
    }
}

# Reference: superseded data files, and nothing else touched
$refSweep = Join-Path $scripts 'Reference'
if (Test-Path -LiteralPath $refSweep) {
    foreach ($f in (Get-ChildItem -LiteralPath $refSweep -File -Force -EA SilentlyContinue)) {
        if ($SupersededReference -contains $f.Name) {
            Doom $f.FullName 'superseded - the master status sheet is at the root of A Writing'
        } elseif ($f.Name -match '^_PaperIndex-\d+\.csv$') {
            Doom $f.FullName 'a stray timestamped copy of the paper index'
        }
    }
}

$rep = Join-Path $scripts 'Reports'
if (Test-Path -LiteralPath $rep) {
    $files = @(Get-ChildItem -LiteralPath $rep -File -Force -EA SilentlyContinue | Sort-Object LastWriteTime -Descending)
    for ($i = $ReportKeep; $i -lt $files.Count; $i++) { Doom $files[$i].FullName 'report older than the newest few' }
    foreach ($sub in (Get-ChildItem -LiteralPath $rep -Directory -Force -EA SilentlyContinue)) {
        Doom $sub.FullName 'subfolder in Reports\'
    }
}

# --- show ---------------------------------------------------------------------

Write-Host ''
Write-Host ("Spring clean: {0}" -f $scripts)
Write-Host ''

if ($rescue.Count -eq 0 -and $doomed.Count -eq 0) {
    Write-Host 'Nothing to do - the five folders are in place and clean.'
    Close-Out
    return
}

foreach ($r in $rescue) {
    Write-Host ("  KEEP   {0}   ->   Reference\" -f (Split-Path -Leaf $r.From))
}
foreach ($d in $doomed) {
    $rel = $d.Path.Substring($scripts.Length).TrimStart('\', '/')
    Write-Host ("  BIN    {0}   [{1}]" -f $rel, $d.Why)
}

Write-Host ''
Write-Host ("{0} item(s) to the Recycle Bin, {1} moved to Reference\." -f $doomed.Count, $rescue.Count)
Write-Host 'Deleted items are recoverable from the Recycle Bin.'
Write-Host ''

if (-not $Apply) {
    if ($NoPause) { Write-Host 'Preview only - nothing was touched.'; return }
    $ans = Read-Host 'Go ahead? (y/N)'
    if ($ans -notmatch '^[Yy]') { Write-Host 'Nothing changed.'; Close-Out; return }
}

# --- act ----------------------------------------------------------------------

$onWindows = if (Test-Path Variable:\IsWindows) { $IsWindows } else { $true }
if ($onWindows) { Add-Type -AssemblyName Microsoft.VisualBasic -ErrorAction SilentlyContinue }
$canRecycle = $onWindows -and ($null -ne ('Microsoft.VisualBasic.FileIO.FileSystem' -as [type]))
$fallback   = Join-Path $scripts '_Deleted'
if (-not $canRecycle) { Write-Host 'Recycle Bin unavailable - items move to _Deleted\ instead.' }

$kept = 0
foreach ($r in $rescue) {
    $parent = Split-Path -Parent $r.To
    if (-not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
    try {
        if (Test-Path -LiteralPath $r.To) { Remove-Item -LiteralPath $r.To -Force }
        Move-Item -LiteralPath $r.From -Destination $r.To
        Write-Host ("  kept  : {0}" -f (Split-Path -Leaf $r.From))
        $kept++
    } catch {
        Write-Host ("  FAILED: {0}   ({1})" -f (Split-Path -Leaf $r.From), $_.Exception.Message)
    }
}

$gone = 0; $failed = 0
foreach ($d in $doomed) {
    if (-not (Test-Path -LiteralPath $d.Path)) { continue }
    $isDir = (Get-Item -LiteralPath $d.Path).PSIsContainer
    try {
        if ($canRecycle) {
            if ($isDir) {
                [Microsoft.VisualBasic.FileIO.FileSystem]::DeleteDirectory(
                    $d.Path,
                    [Microsoft.VisualBasic.FileIO.UIOption]::OnlyErrorDialogs,
                    [Microsoft.VisualBasic.FileIO.RecycleOption]::SendToRecycleBin)
            } else {
                [Microsoft.VisualBasic.FileIO.FileSystem]::DeleteFile(
                    $d.Path,
                    [Microsoft.VisualBasic.FileIO.UIOption]::OnlyErrorDialogs,
                    [Microsoft.VisualBasic.FileIO.RecycleOption]::SendToRecycleBin)
            }
        } else {
            if (-not (Test-Path -LiteralPath $fallback)) { New-Item -ItemType Directory -Path $fallback -Force | Out-Null }
            $dest = Join-Path $fallback (Split-Path -Leaf $d.Path)
            if (Test-Path -LiteralPath $dest) { $dest = $dest + '-' + (Get-Date -Format 'HHmmss') }
            Move-Item -LiteralPath $d.Path -Destination $dest
        }
        Write-Host ("  binned: {0}" -f (Split-Path -Leaf $d.Path))
        $gone++
    } catch {
        Write-Host ("  FAILED: {0}   ({1})" -f (Split-Path -Leaf $d.Path), $_.Exception.Message)
        $failed++
    }
}

Write-Host ''
Write-Host ("Kept {0}, binned {1}, failed {2}." -f $kept, $gone, $failed)
if ($failed -gt 0) { Write-Host 'A failure is usually a file still open. Close it and run this again.' }
Write-Host ''
Write-Host '<number>.Scripts now holds:'
Get-ChildItem -LiteralPath $scripts -Force | Sort-Object Name | ForEach-Object {
    Write-Host ("   {0}{1}" -f $_.Name, $(if ($_.PSIsContainer) { '\' } else { '' }))
}
Close-Out
