---
title: "Investment Appraisal Options"
---

**Investment Appraisal Options**

+---------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **Options**               | Net Present Value                                                                                                                | Hurdle Rate                                                                                                                                                        | Risk Opportunity Analysis/ Decision making under deep uncertainty |
|                           |                                                                                                                                  |                                                                                                                                                                    |                                                                   |
|                           |                                                                                                                                  | Option a) Total economic return                                                                                                                                    |                                                                   |
|                           |                                                                                                                                  |                                                                                                                                                                    |                                                                   |
|                           |                                                                                                                                  | Option b) Net social return (Total economic return – Private return)                                                                                               |                                                                   |
+===========================+==================================================================================================================================+====================================================================================================================================================================+===================================================================+
| **Perspective**           | Money-Project-Money                                                                                                              | System\*-Project-System\* (\*measured financially)                                                                                                                 | System-Project-System                                             |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **Risks/Management Need** | Low                                                                                                                              | Medium                                                                                                                                                             | High                                                              |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **Non-Fiscal Revenues**   | Yes                                                                                                                              | No                                                                                                                                                                 | No                                                                |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **Example**               | Cheap mitigation: Replacing one electricity system with a cheaper clean one (eg RE)                                              | Investment in education versus public health                                                                                                                       | Investment in adaptation; industrial policy                       |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| **Procedure**             | Calculate the net profits after financing. Accept projects with \>0 present value. Potentially crystalize the gains immediately. | Rank all the projects in the system according to social return or net social return and pick the top ones up to some hurdle rate (greater than the borrowing rate) | To be discussed                                                   |
+---------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+

D
