---
title: "Dirk Course"
---

# 

# Diamond-Mirlees: Don’t tax production, tax consumption.  Frascati menu, OECD.

#  Elasticities

Different elasticity. Need to take into account.

Equivalent of carbon price.

Drill deeper into elasticities.

ETS & Carbon tax are different.

Growth implication.

Deadweight loss rises in the square of the carbon price.

Growth cost for emissions trading.

Dependence on business cycle.

Rai Cheti. Respond differently to prices.

---------------------

Waterbed effect, Stanford professors: Making Climate Policy work.

ETS is moved around by other things. Stringency of ETS on its own.

------

Land use. Should we include land uses?

------------------------

Forward looking regulation.

Liquidity problems.

Frequent problem in energy economics.

---

Use of the revenues.

# Revenue Potential of a Carbon Tax

**nformal** Cover the informal sector: avoid large distortion (very high rates -\> Laffer?). Focus on carbon intensive activity: limited tax base.

**Absorption capacity**. Maybe distortions rise?

**Political Economy**: Don't complain about the theatre. Firm-level Political Economy.

 

***Revenue potential.***

**Have a target (Public finance consequences of the target).** Reduce revenue need from conventional taxes. How large? Estimates from Paris Agreement? 1-3% of GDP in revenues.

How steady is the revenue stream? Steady, but not counter-cyclical.

 

Broad coalition of support that is beyond the environmentalists?

Size of governent: contestation of Coase.

Feebates.

Double dividend? To meet

**Revenue Stability**: Binary Panics.

**Carbon tax is eroding its own base**.

 

CRITICISM: Fiscal addiction.

Base x Rate

It takes time. Base erosion.

 

CRITICISM

Protection: exemptions.

OBR does forgo revenues.

Exemptions are being phased out.

Rates with raise over time. Start in the middle.

Go in and keeping steady.

CO2 is a stock externality.

Political economy: rising over time (because it gets old?)

Global level.

Whether the finance minister gets reelected in 3 years.

 

LINK TO STABILISATION OBJECTIVES. Revenue Stabilisation: the automatic stabiliser. Contrinute to long term output .

 

Direct taxes and investments. Victims are more credit. Revenue stability over the business cycle.

 

Political economy

What is the end game for environmental

 

Physical. Ad valorem on the price of the good.

 

Value added Taxes: Very long term.

 

 

Citizen's Justice Perspective: Carbon is a user fee.

 

User fee. Revenues belong to everyone. Rebate in terms of per capita trasnfers.

 

Had revenue expectations. Phase out of a fuel subsidy. Paid revenue to citizens, bottom 80%. TO accounts specially set up in the name of such citizens.

 

Unlocking these accounts, unlocking fuel prices.

 

NEW SOCIAL CONTRACT

From 'get out of the way'

 

Fires together wires together. -\>

 

 

DON'T AGREE.

If communicated well.

If they buy into the vision, then would be disappointed otherwise.

 

***TRUST!!!!!!!***

 

Uncertainty

 

---\> Off topic. Competitive advantage in reliable store of value. Money illusion.

 

Have a picture. Benefits and taxes are unlocked together.

Justice perspective.

 

Next big step that follows from this.

 

The power of prices.

 

CRITICISMS: Macro-political economy.

Micro-political-ecomomy works well.

 

Antedating.

 

Criticisms:

Green bond strategies.

#  

# PE of Tax Changes

Budgeting:

 

End the out of budget games. Finance ministry needs to hold environmental ministry to account.

UNDP and Env dept. Environment budgeting: greenwashing tool

Climate positive and climate negative expenditures. What within the budget is on green things.

No proof that green expenditure

Relative amounts matter.

Expenditure: Solar from 1994. Implicit subsidies for . Total amount can matter.

By and large relative

Bureaucratic institution: how much spend on green things.

 

Spending: Recognizing climate positive as well as climate negative.

Tax expenditures and expenditures to be the same. Wave contribution to PIT. Direct expenditures: very good. Indirect expenditures: very bad.

Large chance that. Don't track tax expenditures. Who benefits from tax expenditures?

 

Climate budgeting. Climate negative expenditures.

 

Reduced VAT rate. Unpriced externalities.

Not how property is defined. State is doing things, in whatever direction it acts?

Inaction is a sort of action.

 

Include as an annex unpriced externalities: help in the political economy.

---------------------------

 

Conservative approach to budgeting. If it is November. They have an interest is spending the money. If they have lower expensive. People want to spend at the end of the FY. Especially

Env issue would like to say it's a rising issue. Spending on A and B.

 

Mutual commitment is needed.

 

Current environmental tax base. Fuel and carbon are the same tax base.

Green investment -\> Stable price signals needed. Derisking from fiscal policy into the future.

Carbon prices from existing taxes on fuel carbon and commodities?

 

Are there any special rates?

Diesel per car: diesel cars are more expensive.

 

Marginal Abatement Costs are not equalised.

 

Look beyond the tax. Deductable: Triple dividend to the finance minister:

1.  Revenues

2.  Climate Improvement

3.  Equity Improvement

4.  Simplify

Dabla Norris Tax [*https://www.imf.org/external/pubs/ft/sdn/2015/sdn1513.pdf*](https://www.imf.org/external/pubs/ft/sdn/2015/sdn1513.pdf)

 

Same R&D tax deduction under the corporate income tax.

 

Technology neutral. Use a major way to shift income when companies.

 

Frascati menu

 

Design setting principle: Climate Target, Base and Rate.

 

Broad tent, where everyone supports, bringing out things that non-environmental

Motivate with efficiencies of the existing tax system.

Libertarians, Capitalists.

People who care about effort. Proud about work.

 

Build a major state. We need to overcome certain existential challenges.

 

Growth model: effort innovation, productivity (includes formality). Taxes on the fruits on the production, not on inputs.

 

Is the structure of the tax system aligned with the growth objectives of the country?

 

Broader interest

Long term structural change. Long term output potential with the world economy.

 

What are your objectives? What is the development strategy?

 

Planning commissions are powerful. Are there objectives about structural change?

Discuss in the same room.

 

---------

 

Motivate by cobenefits

 

 

 

Rich are hurt. Build awareness that existing system is inequitable.

Framing existing tax system for the long term objectives that the country has.

 

Not consistent with the value

External balance. Sending so much money sending oversees.

Could export a lot more fuel. Set up the clearly inefficiencies for the current system.

 

Institutional reforms.

Nobody feels responsible for environmental reforms. Who is responsible for environmental taxation. Storyline, when it is an environmental tax.

Stir the different policies into the

Institution that has a mandate and responsibility according to the polluter pays. All the specific rate instruments.

 

Consumption taxes: Ad valorem: plus per physical unit.

 

Fuel and not carbon.

 

Polluter pay: who is in charge of putting that principle into place.

Who commits to enforce the polluter pay. Political responsibility.

 

Tax plus externality. Climate budgeting. Political accountability. Require an annual annex to the budget. Indirect expenditures. Accounting for the difference to polluter pays.

 

What is the number? Make the case. Approximately right and not precise. Remaining technology failures. Ever bigger. The total

 

I can't sink a low carbon investment if I don't know.

 

 

Commitment devices into the future. Sustainability linked bond. Certificates for Difference.

 

 

Launch is simultaneous. If cash transfers are simultaneous, turning around the endowment effect.

 

Confronting - raise taxes and get . Choice is between raising this tax and that tax. Take people away from

 

Avoid legal earmarking.

 

Uniform carbon pricing. Still not be naïve. Optimal first best tax reform. Do not use exemptions.

For sensitive sectors: output based rebates - per unit of good. Don't exempt the carbon sector: put a OBR. Incentive to use as little as possible, produce as much power as possible.

 

Strengthen the cement sector. Produce as much cement as possible, with as little emissions as posible.

 

Tech policy: feebates.

 

 

Upstream taxation, downstream

Finance ministry, line ministries. You have a decarbonisation strategy.

No revenues for environment ministry.

Env outcomes.

 

Strategic investment with a structural need.

Debt finance: future generations benefit for climate. Industrial structure to change. Debt that we issue today that the future. Also case for more general financing.

 

Cash transfers: salient way to trasnfer benefits. Cash transfers in the future.

 

Rebate, when I am working on the fuel tax. Provide for rebate to additional adoption of air control equipment. China, electricity for running the equipment.

 

Aim for full coverage of taxation. Minimize use of offset systems.

 

Full coverage. Tax upstream, covering the whole of the economy.

 

Cost of the internalisation exceed

 

Is it approximately, A or approximately B? If there is some movement towards that.

 

The private sector, can find out new ways to do things.

 

Taxing olga

 

 

Rebates.

 

# Rebates

> Tax incidence: Dirk asserts that it doesn't matter where in the supply chain this should fall.
>
>  

- First best/second means something technical in economics, 

- What if the companies are credit constained? The argument we shouldn't withdraw funds is not bogus in this case.

- What about monopolistic situations? In that... by Stephen John StrettonStephen John Stretton12:27 PM\
  What about monopolistic situations? In that context, the 'it doesn't matter where you apply the tax' doesn't apply right\>

# Summary of Last Timne

**Summary of last time**

Revenue Subsidy

Broad Tent

Cobenefits

Institutions want Money

False Expectation that there is climate finance, and that it's costly -\> no action unless climate finance.

Games playing out: earmarking in a fund.

Funds: low tax rates.

--------------------

Change in sectoral orientation of the economy.

Change in production methods within sectors.

----------------------

Change with production methods within. CORSIA system. Only prices emissions within current emissions.

----------------------
