---
title: Draft List of Transformational Climate Policy Reforms Backed-up by EFI GP Programs
---

# 

# Selectivity Criteria

Setting out a list of policy reform archetypes justifying top-up climate finance requires clear selection criteria. One candidate criterion is the extent to which a policy reform generates spill-over benefits to other countries. That criterion, however, has the downside of requiring teams to show how other countries benefit, whereas climate action in developing countries should continue to focus on aligning climate action with domestic goals. It is laudable when a country undertakes climate action yielding global benefits, but to sustain climate action in the long run, as well as to align with core EFI objectives, reforms must be designed for domestic economic benefits. Here we therefore propose selecting policy reforms based on another criterion: the extent to which a reform generates transformational change.

We define transformational change in accordance with the WBG Guiding Framework on Climate Finance.[^1] A reform is transformational if it significantly reduces the barriers to implementation faced by future climate-related programs or projects. In other words, the reform generates increasing returns to scale by reducing future costs. It not only delivers climate benefits today, but also makes it easier to implement future programs or projects that will reduce emissions or boost resilience.

Mitigation-related reforms are transformational when, once implemented, barriers to implementation have been reduced for subsequent mitigation projects, thereby also reducing future needs for concessional climate finance support. This is generally the case if the program fixes market failures (e.g., removes disincentives created by distortive tax systems that promote fossil fuels), builds institutional capacity (e.g., creates a functioning regulator for energy markets), or generates innovative spillovers (e.g., demonstrates the viability of a sustainability-linked financial instrument in a country). Ideally, reforms help reach a “tipping point” beyond which future mitigation projects will not require concessional climate finance (i.e., when a low-carbon option becomes least-cost and can attract commercial finance).

Resilience-related reforms are transformational if they (A) improve the system-level stability of an economy against “cascading climate damages” and “compound damages”[^2] of climate shocks (economy-wide climate impacts), or (B) make it significantly easier and cheaper to adapt to climate change and reduce future climate and disaster risks (sectoral physical impacts), and thereby reduce future needs for concessional climate finance. Criterion (A) is satisfied when a reform improves the system resilience of an economy to recover from large shocks without hysteresis effects (e.g., improves debt sustainability, financial stability, insurance, countercyclical fiscal policy and generally the creation of fiscal buffers, and social security). The transformational potential of the reform can be evaluated, ex ante, through system-level stress tests for large shocks, identifying whether they have persistent detrimental effect for long-term socio-economic development. Criterion (B) is satisfied when a reform fixes market failures (e.g., removes property tax incentives to build housing in flood plains), builds institutional capacity (e.g., creates a risk-informed land-use plan or improves building regulations), or generates innovative spillovers (e.g., develops a hazard map that can be used for all future investments). The transformational potential of the reform can be evaluated, ex ante, based on its impacts on barriers to implementation that future programs or projects will face (e.g., the effects on future prices of a key technology, or on implementation capacity in a country).

A further criterion for the transformative impact of both mitigation and adaptation reforms is whether the reform type is politically sustainable in a developing-country context. For EFI operations in developing countries, economic development is the core priority. It is not realistic for poor countries to sustain climate policy reform types that slow domestic economic development. Therefore, a transformative climate policy reform must combine good climate and development outcomes.

The below list is a tentative draft. Going forward, two refinements are recommended. Firstly, EFI may wish to start with a narrowed-down version of the below list that focuses on those reform archetypes for which policy impacts can already be quantified. EFI could first leave out reforms for which such quantification methodologies do not yet exist while expediting efforts to create these. Over time, the archetypes of policy reforms that are eligible for top-up climate finance could then be expanded, while starting from a subset for which the transformational impact is already best-established and for which consultations with clients and donors should hence be easier. Secondly, the list can be further refined through additional consultations across GPs.

# Fiscal Policy

## Carbon Pricing

Carbon pricing has transformative impact by incorporating climate constraints into profit maximization. This policy comes in the form of “direct” and “indirect” carbon pricing. Direct carbon pricing includes (1) carbon taxes and (2) emissions trading systems and (3) tradeable performance standards. These instruments price goods in proportion of carbon content and have an explicit climate purpose. Indirect carbon pricing covers fiscal instruments that raise the price of carbon-intensive goods without proportionality and often targeting other main purposes. These policies include (1) raising taxes or lowering subsidies on fuels or other carbon-intensive commodities (including deforestation-related agricultural and mining commodities), (2) emissions feebates, (3) removing fuel price ceiling rules, and (4) removing restrictions to electricity cost passthrough including framework regulations on associated Power Purchase Agreements. There is evidence that direct carbon pricing can have greater impact on emissions than indirect carbon pricing, but that indirect carbon pricing is more widespread in developing countries, can be more easily sustained by established administrative systems, yield lower risks for revenue management, and often yield larger reform sizes. Therefore, this list considers both reform types as potentially transformative. The World Bank would be a potent partner for this reform archetype because it has impact assessments available for all client countries. Therefore, carbon pricing is proposed as a key reform archetype to be included in list of DPF prior actions qualifying for top-up climate finance. Given the wide set of these policy instruments, the proposed list could include a quantitative criterion specifying that eligible reforms need to yield a threshold increase in overall, economy-wide carbon pricing. The required methodology[^3] is ready.

## Fiscal Technology Policies

Fiscal policies beyond carbon pricing are generally necessary, especially in developing countries. The turnover rate of emissions-intensive durable assets is often low, and durables often continue to be used even when they pose high operations cost. Such situations create poverty traps and lock in emissions. For example, citizens can keep using a gas-guzzling car even when fuel prices are high because they are credit-constrained in upgrading to more fuel-efficient vintages. Likewise, energy-inefficient machinery can be used long past its economic lifetime. Therefore, it can be transformational for governments to reform taxes, subsidies and tariffs on durables that have large emissions impact over their lifetime. This reform archetype includes scaling taxes on durables according to emissions (e.g., taxing cars by CO~2~/km, taxing properties by energy consumption) and fiscal incentives for green technologies (e.g., reduced import tariffs on solar panels), or Contracts for Difference (see below).

## Ecological Fiscal Transfers

In many countries, climate policy targets are set at the national level, but their implementation depends on decisions by subnational governments. These often lack incentives, e.g., when subnational enforcement of a forest law reduces short-term local economic opportunities and associated subnational revenues. But there is a tested solution to these institutional problems. In many developing countries, subnational governments receive budgets from formula-based intergovernmental fiscal transfer systems. Central governments can incorporate environmental progress indicators into these formulae, so the size of budget transfers varies according to the subnational governments’ attainment of agreed environmental objectives. This can be a powerful and revenue-neutral incentive system. It works like the WBG’s own formula-based IBRD/IDA envelope system where country allocations vary depending on CPIA scores. There is evidence of transformative impact from these reforms, especially in addressing land-use emissions, and the WBG has the needed technical capacity to support such reforms.

## Climate-Smart Fiscal Rules

Many debt-constrained countries need fiscal rules to rebuild strong public finances. In many cases these fiscal rules work by constraining public spending. If so, the design matters greatly for both fiscal and climate objectives. There is evidence that many governments react to expenditure constraints by cutting long-term public investments rather than short-term government consumption. But cutting public investments often causes a more persistent reduction in long-term output potential than cutting government consumption, thus compromising the long-term debt-to-GDP ratios which the fiscal rule seeks to improve. Such side effects of fiscal rules are also a problem for climate action because government expenditures on climate typically come in the form of long-term investments rather than government consumption. Therefore, both fiscal/growth and climate objectives can be supported by a more careful design of fiscal rules which differentiates by the type of government expenditure. Fiscal rules can be designed to put greater constraints on government consumption than on long-term public investments that prove a persistent contribution to economic growth. These fiscal rules are called “Golden Rules”. Climate-related investments can be included in a list of investments contributing to long-term growth as they raise the resilience of the country to climate shocks and the changing opportunities in a decarbonizing world economy. These “Green-Golden Rules” are transformative because they improve the foresight of fiscal policymaking, safeguard long-term sustainability objectives during times of short-term crisis, apply at a large scale, and improve the predictability of fiscal policy and its associated market signaling power. The WBG has the needed capacity for this policy reform archetype due to its long-standing experience with fiscal rules, and it has the endurance to accompany these changes over time because doing so aligns closely with needed reforms for addressing the current twin crises of rising public debt and decelerating long-term growth potentials.

## Green Public Procurement

There is strong evidence of increasing returns to scale in both mitigation- and adaptation-related technologies. These increasing returns apply not just at a global scale, where developing countries are often insufficiently large to make a difference, but also on the local scale due to the existence of fixed costs to local adaptation of technologies and network externalities for users. This means that, also in developing countries, stimulating green growth requires technology adoption at a minimum efficient scale. That nonlinearity, in turn, is a key barrier to establishing new low-carbon climate-resilient markets. To overcome these barriers, the state can provide an initial push to green products and practices. This can be done by incorporating climate-related criteria into public procurement systems. The state’s purchasing power has a key potential for developing green technologies to the minimum efficient scale from which onward unit costs are sufficiently low for free market penetration. Additionally, the signaling power from the government’s commitment to these procurement practices helps coordinate market expectations for the breakthrough of these technologies, leveraging further private investments. There is ample evidence and best-practice examples for green procurement, indicating low administrative barriers for transformative impact. Also, in many value chains and developing countries, there are existing private-sector sustainability certification systems. The public sector can reuse those systems, lowering administration costs, and creating transformative incentive effects for the market penetration of these certification systems. The World Bank has the needed capacity for this policy reform archetype from its experience in reforming public procurement systems, as well as a program on private-sector business environments that would enable linking these procurement practices with private-sector sustainability certification systems.

## Climate Budgeting and associated Climate-Smart Public Financial Management

Notwithstanding the arguments made above on possibilities to reduce climate-related expenditure needs, climate action is widely seen to require large public investments. Given the scarcity of public funds, these investments must become much more transformational. But many Finance Ministries lack even basic systems for tracking, planning and surveilling climate-related public expenditures, which are often scattered across line ministries. The World Bank, UNDP, OECD and others have long assisted Finance Ministries in establishing such systems. These reforms would continue to be supported through this program. However, to be eligible for top-up funding, reforms would need to satisfy a set of minimum quality standards. (1) Many existing programs of Climate Budgeting in developing countries count only climate-positive expenditures, when low-carbon structural change is instead determined by relative public expenditures for climate-positive and climate-negative outcomes. For example, many Climate Budgeting programs would only count a subsidy for renewables but not one for coal, when the two may cancel out each other. To classify as a transformational reform, Climate Budgeting reforms supported through this program would track the relative spending towards climate-positive versus climate-negative structural change. (2) Many existing Climate Budgeting programs do not account for tax expenditures. Yet, the majority of climate-negative public expenditures in most countries is undertaken through tax expenditures rather than direct expenditures. Without incorporating tax expenditures, it is not possible to verify how overall fiscal incentives change. Therefore, only Climate Budgeting systems that incorporate tax expenditures would be considered as transformational policies eligible for top-up. With these changes, the World Bank would have significant experience and capacity to support another key reform archetype across countries.

## Public Investment Management with Long-Term Strategies

To reach climate targets, Finance Ministries seek the least-cost climate investments. Unfortunately, identifying those least-cost options has proven hard. The determination of least-cost option critically depends on the time horizon considered for the amortization of investments. Traditionally, policymakers have chosen least-cost investments by calculating Marginal Abatement Cost Curves – the so-called “McKinsey approach”. But a key finding from the climate economics literature of the last 30 years and the CCDRs is that minimizing the total cost of climate transitions requires going beyond marginal cost calculations and costing technology pathways over a longer time horizon. For example, the US Inflation Reduction Act or the German renewable energies laws specifically targeted technologies that have high unit costs to bring those costs down with cumulative scale. The World Bank is providing countries with support to operationalize this approach by designing Long-Term Strategies (LTS). The next step is then to use these LTS for reforming public investment management. The latter is a policy reform that can be financed. To be impactful, what is important here is not the LTS itself (which is just a document) but its operationalization. To be counted as transformational and eligible for top-up climate finance, such DPF prior actions would therefore not focus on the development of an LTS itself but the operationalization of LTS in public investment management.

## Management of Climate-Related Fiscal Risks and Climate-Impacts for Debt Sustainability

Climate change, domestic climate policy and global decarbonization are increasingly causing fiscal risks. Yet, few client countries are considering these risks in their fiscal risk management strategies. Even in countries that are frequently hit by natural disasters, forward-looking management of associated fiscal risks is rare. There is a discrepancy here between national central banks and finance ministries: 125 central banks and national financial supervisory authorities are already warning of climate impacts on financial stability (NGFS) with the Bank of International Settlements warning of an unprecedented and potentially near-term financial crisis caused by climate transitions. It is well known that financial crises tend to yield large fiscal risks. Yet, finance ministries in the same countries of those concerned central banks do not consider these risks in their fiscal risk management systems. Meanwhile, Fitch, Moody’s and S&P all warn that climate vulnerability is affecting sovereign risk ratings, which can already be seen in debt financing costs. It is therefore essential to support countries in reforming fiscal risk management and debt management to account for climate-related risks. The World Bank is currently developing this technical capacity and has existing global programs to leverage for supporting this reform archetype.

# Trade Policy

## Tariff Reform

In most countries, green technologies face higher tariff barriers than high-carbon goods. This amounts to more than USD 500bn per annum in price incentives against decarbonization. Furthermore, as carbon is concentrated in upstream stages of global value chains, this tariff structure increases the barriers for developing countries to diversify from basic resource extraction. This tariff structure is thus both a climate and a development problem. It should then be included in a list of transformational reforms. Given the large number of tariff rates that countries could change, determining whether a reform is transformational for climate action would require a quantitative threshold for impacts on economy-wide incentives.

## Sustainability Certification 

In most carbon-intensive Global Value Chains, major private-sector initiatives are underway to identify, standardize and certify available sustainable production methods. The WDR 2019 emphasizes the importance of further supporting these certification efforts, but also for complementing certification with public policy. There are a clear set of policy reforms that countries can undertake to unblock sustainability certification systems to integrate into green value chains.

## Reforms adapting to Carbon Border Adjustment Mechanisms 

The World Bank is increasingly advising client countries on impacts of Carbon Border Adjustment Mechanisms that are being introduced in large consumer markets (EU, UK, with others impending). These systems recognize policy reforms in developing countries, but raise multiple complexities. Client countries will need technical support in designing climate policy reforms that help them secure those more favorable trade terms.

## Reforms adapting to Market Access Rules controlling “Imported Deforestation”

Many client countries are affected by new legislation in the EU, USA, UK and Australia constraining market access for commodity exports associated with deforestation. Client countries have multiple policy reform options to cut down on deforestation linked to their exports. Supporting countries with implementing such reforms can be transformational for combining climate mitigation with maintaining free trade. For example, Cote d’Ivoire and Ghana currently face potentially disastrous consequences of losing market access to the EU and USA due to deforestation and child labor problems in the cocoa value chain. The World Bank has the needed experience to support client countries with policy reforms reducing deforestation from export goods.

# Financial Sector Policies

## Greening National Development Finance Institutions

Institutional reforms to the world’s 450 national development finance institutions (NDFIs) can promote sustainability goals worldwide. Sustainability often requires long-term funding and stable market signaling, and NDFIs can offer stable, long-term funding in national currencies that reduces uncertainty, mitigates external vulnerabilities, and promotes diversification, innovation and crowding-in. In addition, NDFIs can insulate technology choices from lobbying pressures and develop the necessary technical capacity for establishing low-carbon markets. Moreover, NDFIs can sustain stable structural change along election cycles, which can be a greater challenge for Finance Ministries acting alone. There is an opportunity for DPF-supported institutional reforms to align existing NDFIs with national climate goals, refocusing operations and portfolios accordingly.

## Climate Bad Banks

Global low-carbon structural change creates major spillover risks for stranded assets in developing countries. There is a broad consensus among central banks and financial supervisory authorities on the ability of national policy reforms to reduce exposure to these risks. One such strategy for reducing this risk exposure is the use of Bad Banks to cleanse the balance sheet of economic agents from elements endangering their financial viability. For example, in the 2007/2008 financial crisis, Bad Banks were established as purpose vehicle to offload toxic assets from subprime mortgages. While such policies incurred public costs, they are credited for having prevented an even worse financial crisis. Some countries have started applying this model to carbon-dependent assets at risk of the global transition. In Poland, for example, coal power stations are currently becoming stranded assets and are burdening the balance sheets of the power sector to move into renewable profit opportunities. The government therefore created a Bad Bank-type vehicle for offloading those stranding assets. More generally, Climate Bad Banks can house those assets exposed to transition risks. Once the assets are transferred, the Climate Bad Bank may have three different goals. It can seek to liquidate the assets as quickly as possible (by selling them outside the country to investors willing to bear that risk), carry out proper asset management to make non-performing assets eventually perform, or conduct an “extinctive management” of the assets, for the soft-landing of dying businesses. Such policies can help unstuck financial institutions to expand low-carbon investments, and reduce the aforementioned crisis exposure. Early policy action can avoid transition-exposed assets being transferred to less regulated and less solid financial agents. Their optimal design relies on three main - intertwined - challenges for such institutions: of economic efficiency, justice and governance. DPFs could help client countries in adopting best-practice designs.

## Green Taxonomies and associated Implementing Regulations

Many developing countries use green bonds for mobilizing low-carbon investments from the private sector. However, the development of efficient and transparent green bond markets requires identifying what counts as green. This can be achieved through “green taxonomies” – which define criteria for evaluating sustainability impacts of financial assets. For a decade now, such taxonomies have been used by the private sector – now they are efforts to align with public policy. Finance ministries and central banks have now developed official taxonomies in several jurisdictions (e.g., China, Colombia, Malaysia). Such strengthened taxonomies can become key instruments to mobilize climate finance, including for green budgeting. But implementing such reforms requires careful policy design. It is especially hard to establish green taxonomies in “hard-to-abate” sectors where the low-carbon transition will take time such that activities today are still highly carbon-intensive, and where making the change requires especially large investments. In these sectors, it is essential for forward-looking firms to be able to signal to financial markets when they are gradually becoming sustainable. A strong green taxonomy recognizes the need to “transition away” from a legacy of unsustainable activities, and that this transition also requires massive investment. This is especially true in emerging economies, which are generally more carbon-intensive. The Sustainable Finance Disclosure Regulation provides a scalable template for improvements in the transparency of the market for sustainable investment products, to prevent greenwashing and to increase transparency around sustainability claims made by financial market participants. World Bank DPFs could help implement this regulation in developing countries, and thereby help client countries avoid being disconnected from growing green financial markets.

A key novelty in green finance is the emergence of Sustainability-Linked Bonds. Different from green bonds, SLBs are not restricted to specific projects or expenses – instead, their payout to bondholders depends on the agreed-upon performance indicators, which is an incentive instrument. This means that SLBs can be part of a broader shift from an overreliance on climate project finance to policy incentives. However, floating Sustainability-Linked Bonds requires the introduction of measurable Key Performance Indicators, and such KPIs must be designed in a robust manner and align with country contexts. An important precondition for robust KPIs is the development of proper data infrastructures and associated institutions. Sustainability-linked instruments can then offer financial rewards to borrowers based on their success in achieving predetermined sustainability objectives. These various steps can be supported through the World Bank. For instance, Uruguay recently implemented such policy and institutional reforms which then helped successfully issue its first sustainability-linked bond. This is therefore another potential transformational policy reform archetype for top-up climate finance.

## Development of Climate-Related Financial Metrics, Certification Labels, and Disclosure Standards 

Public authorities can play a crucial role in defining disclosure and reporting standards in nascent green financial markets. Such reforms can improve transparency, increase awareness of climate-related risks and investment opportunities, facilitate communication with stakeholders, and ultimately enable the efficient allocation of capital towards a low-carbon and climate-resilient economy. Financial regulators, for instance, can set specific disclosure requirements for financial institutions, while conduct or capital markets regulators can support and enforce sustainability reporting and labeling practices for listed companies. Several international initiatives are underway to establish such regimes and WBG DPFs can help client countries with national implementation. DPF reforms can also help connect client countries with emerging international practices in risk rating, external review and verification of climate-sensitive assets.[^4]

## Green Asset Purchase Programs

Asset purchase programs like Quantitative Easing are only used in some developing countries, but where they are used, a key reform can be to incorporate criteria for climate-related asset risks. Green asset purchase programs, or Green Quantitative Easing, incorporate preferential targeting of low-carbon assets. The reforms have three direct impacts. First, they contribute to expanding the central bank’s balance sheet by creating new bank reserves in exchange of the assets purchased by the central bank. Second, they contribute to changing the eligibility criteria of banks’ assets that can be purchased by the central banks. Third, they lead to an increase in banks’ liquidity, thus increasing the amount of money in the economy. These impacts give rise to new transmission channels which can address risks that climate change and climate transitions poses to monetary policy.

## Regulatory Frameworks for Trading in Climate-Impacted Commodities Markets

Climate change is expected to exacerbate fluctuation in commodity markets, which can have profound economic and poverty implications. Countries are therefore interested in reforms to mediate such fluctuations, including fluctuations for non-climate reasons which compound the climate-related fluctuations. One aspect here is the increased financialization of global commodity futures markets, as commodities are becoming an asset class for speculative purposes. Financialized commodity markets can improve market liquidity and price discovery and allow financial market participants to hedge their investments. Yet, regulation and supervision of commodity derivatives markets, notably to strengthen transparency and address market abuse, is important to avoid price volatility and misuse. This includes improving transparency of information about commodities (spare capacity, stock holdings, short-term demand forecast), information on commodity derivatives markets with respect to position-taking by different market participants, setting position limits, and strengthening market surveillance authorities to avert price collapses and bubbles.

## Climate-Resilient Debt Instruments

Many climate-vulnerable countries also face high debt levels, which raises concerns of climate shocks unleashing cascading damages for financial stability. One reform type for mediating these problems is Climate-Related Debt Clauses (CRDCs). This refers to the forward-looking incorporation of contingency clauses in debt instruments which allow the deferral of a country’s debt repayments in the event of a pre-defined, severe climate shock. As such clauses are priced into debt instruments, they create a form of disaster risk insurance. CRDCs suspend debt service repayments for a pre-agreed period when a pre-defined climate shock hits to free up cash-flow that could be better used to support disaster relief.

## Climate-Financial Risk Assessments

Most policy and institutional action on climate change by central banks and financial regulators will require initial climate risk analyses. Helping clients get started with such analyses can therefore be transformational. To conduct climate financial risk assessments, countries need a framework for forward-looking physical and transition risk scenarios, as well as mapping country-specific transmission channels. The results of these analyses are then published and communicated to stakeholders to facilitate market adjustment such as divestment from carbon-dependent assets. Understanding risk channels and vulnerabilities is essential in informing supervisory priorities and enabling a risk-based supervisory approach. Quantitative assessments are significant in informing supervisory action to provide detailed guidelines for the banking sector on risk management, governance, stress-testing, and reporting. Identifying data gaps is also important in developing a strategy to bridge those gaps, including through guidance on disclosure and regulatory reporting.

# Innovation Policies and Macrostructural Reform

## Institutional Reforms for Creating Markets

Many markets for low-carbon technologies do not yet exist. Often, the rules are not set for low-carbon investment. For example, in many countries, rules for feeding renewable electricity into otherwise coal or gas-dominated grids have not been set, which means that renewables operators have no mechanism to sell electricity to consumers. Furthermore, in many countries, mechanisms for trading low-carbon commodities such as green hydrogen do not exist. A market-creation policy reform can involve developing market trading rules (e.g., auction rules in power markets), creating a market regulator, creating institutions that aggregate demand across users to ensure predictable demand for suppliers to reduce investment risk, and ensuring availability of supply for users by coordinating investment in supply capacity. An example of this is the creation of a facility that clears demand and supply for future contracts of green products to enable the private sector to invest in production and use capital without excessive risk.

## Market Liberalization

Even where low-carbon technologies are least-cost, they can be foreclosed through market access barriers. For example, in many developing countries, electricity markets are operated by state-owned monopolists and do not allow independent producers to feed electricity into the public grid. These market barriers can be motivated by Political Economy: renewable energies can often operate at a smaller scale without traditional SOE structures, so allowing cheap, low-carbon and decentralized energy can upset political power structures. SOEs can prefer to instead stem the low-carbon transitions without new private actors, but then lack the investment capacity to do so, instead perpetuating the status quo. Liberalizing such markets enables other investors, bringing external resources, to participate in decarbonization, and unleash the efficiency of the private market. Reforms then involve abolishing legal barriers to market access, reforming SOEs and regulators.

Market instruments, such as carbon pricing, are typically best combined with reforms of markets to be more market-oriented. In many client countries, there are pre-existing fuel purchase agreements. Power purchase agreement reform can, for example, replace existing contracts with a contract of higher value that avoids obligations of physical delivery or where that delivery can be satisfied from other power sources, such as renewables. It also important that markets are contestable - for example a power market should be accessible to new renewable energy sources, which can often require reforming SOEs and market regulators.

## Public-Private Partnerships for Nascent Technologies 

The costs for many low-carbon technologies accrue upfront. It is sometimes clear that green technologies have the potential to become competitive if deployed at scale, but despite that, the necessary investments may be excessively risky for the private sector to the extent that they deter participation. The public sector can partner with key private sector participants to develop demonstration projects by co-owning innovation risk. This allows to experiment with, demonstrate and expand production scale for green technologies in early stages of development, which brings down costs and risks in such a way that eventually makes them manageable by the private sector alone.

## Contracts for Difference

In many situations of early-stage technology development where technologies are near-competitive, market risk mitigation can be more important to private-sector investors than relative cost minimization. Since low-carbon investments often have a long lifetime, ensuring a stable price over an investment project’s lifetime can be more important than deterring the competition. Excessive uncertainty over the profitability of marginally competitive low-carbon projects generally deters investment. One mechanism that has been successful in crowding-in low-carbon private investment is the contract-for-difference (CFD). In such a contract, a strike price is agreed between an investor and the government through a reverse auction. The contract stipulates that any difference between the future sale price and the strike price must be paid off to the counterpart, depending on whether it is positive (a windfall profit for the private operator is paid back to the government) or negative (the government subsidizes the operator if the sale price declines below the agreed price). The CFD mechanism has driven success in many renewable electricity deployment activities worldwide, and the evidence suggests that it generally works more effectively in scaling up new risky technology than carbon taxes/markets, the latter which can make renewables projects competitive but do not reduce uncertainty. Such contracts provide long-term price certainty, and therefore revenue certainty, which reduces financing costs. These contracts are especially important in high-risk environments, such as developing countries.

## Harmonizing Regulatory Standards

For many green technologies, global initiatives are underway to harmonize regulatory standards and thereby expand market volumes. For developing countries, it is important to sustain and improve access to the Greentech markets of the future by aligning with these regulatory standards. The World Bank can support such reforms. Harmonizing regulatory standards internationally and aligning investment strategies in new technology can help expand potential market volumes for green technologies and products, attract more domestic and foreign investment and reduce costs. This includes trade rules and makes a fundamental component of, for example, Climate Clubs. Partnering on innovation can also involve cross-border knowledge sharing, joint projects and joint infrastructure, which reduce deployment costs.

[^1]: WBG (2018). “Strategic Use of Climate Finance to Maximize Climate Action – a Guiding Framework”

[^2]: See Annex on types of climate risks for identifying focus areas for EFI DPFs.

[^3]: MTI, DEC, CCG & EEX (2023) “Total Carbon Pricing”

[^4]: While credit ratings for corporate bonds and external reviews are widely used in advanced countries, they are missing in many low-income countries. However, as countries promote green finance, external reviewers are needed for ensuring the legitimacy of green bonds. Third-party verification is often used before and after issuing green and thematic bonds to ensure that bond proceeds are managed appropriately, according to the issuer's framework. For asset managers and owners, external verification provides an additional layer of due diligence to ensure that private capital is flowing as intended.
